services:
  db:
    image: postgres:15
    container_name: moneytrack_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moneytrack
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: moneytrack_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/moneytrack
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: moneytrack_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
